cabal-version: 3.0
name:          ip2026
version:       0.1.0.0
build-type:    Simple

library
    hs-source-dirs:
        lib
        src/clase_4
        src/clase_5
        src/clase_6_teorica
        src/clase_7
        src/clase_8_simulacro
    exposed-modules:
        Types
        CalcBox
        Fibonacci
        ContarPalabras
    build-depends:
        base >= 4.14 && < 5,
        HUnit
    default-language: Haskell2010

test-suite unit-tests
    type: exitcode-stdio-1.0
    main-is: Spec.hs
    hs-source-dirs:
        test
        src/clase_4
        src/clase_6_teorica
    other-modules:
        ContarPalabrasTest
        FibonacciTest
    build-depends:
        base >= 4.14 && < 5,
        HUnit,
        ip2026
    default-language: Haskell2010
